Improve zsh configuration
zsh/zshrc: get several configurations from https://github.com/Valodim
zsh/zshrc: add LS_COLORS configuration
zsh/zshrc: add highlight style configuration
zsh/zshrc: add several options
zsh/zshrc: correct GREP_COLOR typo

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -2,10 +2,66 @@ if [[ ! -d $ZSHDATADIR ]]; then
 	mkdir -p $ZSHDATADIR
 fi
 
+# LS_COLORS {{{
+if [[ ! -f $ZSHDATADIR/LS_COLORS/LS_COLORS ]]; then
+	mkdir -p $ZSHDATADIR/LS_COLORS
+	git clone https://github.com/trapd00r/LS_COLORS.git $ZSHDATADIR/LS_COLORS
+fi
+
+zmodload zsh/terminfo || return 1
+
+# only available for 256 color terminals
+if (( $+terminfo[colors] )) && (( $terminfo[colors] == 256 )); then
+	# load trapd00r's LS_COLORS things
+	eval $( dircolors -b $ZSHDATADIR/LS_COLORS/LS_COLORS )
+fi
+#}}}
+
 if [[ ! -f $ANTIGENDIR/antigen.zsh ]]; then
 	mkdir -p $ANTIGENDIR
 	git clone https://github.com/zsh-users/antigen.git $ANTIGENDIR
 fi
+
+# Highlight style {{{
+# variables for zsh-syntax-highlighting
+# ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$ADOTDIR/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting.git/highlighters
+ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
+ZSH_HIGHLIGHT_MAXLENGTH=300
+
+if (( $+terminfo[colors] )) && (( $terminfo[colors] == 256 )); then
+	typeset -A ZSH_HIGHLIGHT_STYLES
+	: ${ZSH_HIGHLIGHT_STYLES[default]:=none}
+	: ${ZSH_HIGHLIGHT_STYLES[unknown-token]:=fg=red,bold}
+	: ${ZSH_HIGHLIGHT_STYLES[reserved-word]:=fg=yellow}
+	: ${ZSH_HIGHLIGHT_STYLES[alias]:=fg=226}
+	: ${ZSH_HIGHLIGHT_STYLES[builtin]:=fg=141}
+	: ${ZSH_HIGHLIGHT_STYLES[function]:=fg=214}
+	: ${ZSH_HIGHLIGHT_STYLES[command]:=fg=118}
+	: ${ZSH_HIGHLIGHT_STYLES[hashed-command]:=fg=119}
+	: ${ZSH_HIGHLIGHT_STYLES[path]:=underline}
+	: ${ZSH_HIGHLIGHT_STYLES[globbing]:=fg=105}
+	: ${ZSH_HIGHLIGHT_STYLES[history-expansion]:=fg=63}
+	: ${ZSH_HIGHLIGHT_STYLES[single-hyphen-option]:=239}
+	: ${ZSH_HIGHLIGHT_STYLES[double-hyphen-option]:=241}
+	: ${ZSH_HIGHLIGHT_STYLES[back-quoted-argument]:=none}
+	: ${ZSH_HIGHLIGHT_STYLES[single-quoted-argument]:=fg=yellow}
+	: ${ZSH_HIGHLIGHT_STYLES[double-quoted-argument]:=fg=yellow}
+	: ${ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]:=fg=cyan}
+	: ${ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]:=fg=cyan}
+	: ${ZSH_HIGHLIGHT_STYLES[assign]:=none}
+
+	: ${ZSH_HIGHLIGHT_STYLES[precommand]:=fg=227}
+	: ${ZSH_HIGHLIGHT_STYLES[commandseparator]:=none}
+
+	# and zle's very own zle_highlight
+	zle_highlight=(
+	region:underline
+	isearch:underline
+	special:bold
+	suffix:fg=76
+	)
+fi
+#}}}
 
 source $ANTIGENDIR/antigen.zsh
 
@@ -67,6 +123,57 @@ if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
 	zle -N zle-line-init
 	zle -N zle-line-finish
 fi
+#}}}
+
+# options {{{
+## directory changing
+# implicit cd if directory is used as command
+setopt autocd
+# make cd behave like pushd, and enable some convenience functions for pushd
+setopt autopushd pushdignoredups
+setopt pushdtohome pushdminus pushdsilent
+
+## completion options
+# list choices if completion is ambiguous
+setopt autolist
+# if a word matches exactly, accept it even if ambiguous
+setopt recexact
+# completions don't have to be equally spaced
+setopt listpacked
+# show file types in completion ( / for dirs, = for pipes, @ for symlinks, etc..)
+setopt listtypes
+
+## interactive type features, mostly zle stuff
+# use '' inside ' quotes to write a single ' character (only interactively!)
+setopt rcquotes
+# allow # for comments interactively (helpful for history annotation)
+setopt interactivecomments
+# require >! to overwrite a file
+setopt noclobber
+
+## globbing
+# enable ^, ~, # and glob flags in glob expressions (oh yes)
+setopt extendedglob
+# sort globs numerically (8 9 10 11, not 10 11 8 9)
+setopt numericglobsort
+# ~ substitution and tab completion after a = (for --x=filename args)
+setopt magicequalsubst
+
+## job control
+# for single commands, resume matching jobs instead
+setopt autoresume
+# list jobs in long format
+setopt longlistjobs
+# notify us about job status changes immediately
+setopt notify
+
+## negatives
+# don't run background jobs in lower prio by default
+#unsetopt bgnice
+# directories don't need to end in a slash
+unsetopt autoparamslash
+# never beep on error!
+unsetopt beep
 #}}}
 
 # Ensure some directories exist.
@@ -151,7 +258,7 @@ if [[ ! ":$PKG_CONFIG_PATH:" == *":$HOME/.local/lib/pkgconfig:"* ]]; then
 fi
 
 # grep color setting
-export GREP_COLOR='1:31'
+export GREP_COLOR='1;31'
 
 # vim settings
 export EDITOR=vim
@@ -266,4 +373,4 @@ if type -p -a mc > /dev/null; then
 	esac
 fi
 
-#  vim: set ft=zsh ts=4 sw=4 tw=0 noet :
+#  vim: set ft=zsh ts=4 sts=4 sw=4 tw=0 noet fdm=marker :
